<Project>
  <PropertyGroup>
    <RestoreUseStaticGraphEvaluation>true</RestoreUseStaticGraphEvaluation>
    <RestoreBuildInParallel>false</RestoreBuildInParallel>
    <BuildInParallel>false</BuildInParallel>
    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
    <InformationalVersion>1.0.1</InformationalVersion>
    <Product>WeezTail</Product>
  </PropertyGroup>
</Project>
