<Project>
  <PropertyGroup>
    <RestoreUseStaticGraphEvaluation>true</RestoreUseStaticGraphEvaluation>
    <RestoreBuildInParallel>false</RestoreBuildInParallel>
    <BuildInParallel>false</BuildInParallel>
    <Version>1.2.3</Version>
    <AssemblyVersion>1.2.3.0</AssemblyVersion>
    <FileVersion>1.2.3.0</FileVersion>
    <InformationalVersion>1.2.3</InformationalVersion>
    <Product>WeezTail</Product>
  </PropertyGroup>
</Project>
